"""empty message

Revision ID: e6122fd8cd98
Revises: 
Create Date: 2023-09-09 11:54:26.116562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6122fd8cd98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_constraint('Show_artist_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Show_venue_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_talent')
        batch_op.drop_column('website')

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Show_venue_id_fkey', 'Artist', ['venue_id'], ['id'])
        batch_op.create_foreign_key('Show_artist_id_fkey', 'Venue', ['artist_id'], ['id'])

    # ### end Alembic commands ###
